name: Compile LaTeX

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX
      run: pdflatex -interaction=nonstopmode -halt-on-error main.tex
